import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#3b494b",
        "on-primary": "#00363a",
        surface: "#131313",
        primary: "#dbfcff",
        "secondary-container": "#ff525c",
        "inverse-primary": "#006970",
        "secondary-fixed-dim": "#ffb3b2",
        "on-surface": "#e5e2e1",
        "secondary-fixed": "#ffdad8",
        "on-secondary-fixed-variant": "#92001e",
        "inverse-on-surface": "#313030",
        tertiary: "#fdf3ff",
        "primary-container": "#00f0ff",
        "on-primary-fixed": "#002022",
        "on-secondary-container": "#5b000f",
        "tertiary-container": "#e9d0ff",
        error: "#ffb4ab",
        "on-background": "#e5e2e1",
        "on-secondary-fixed": "#410008",
        outline: "#849495",
        "on-tertiary-fixed-variant": "#6700b5",
        "on-tertiary-container": "#8523dd",
        "surface-bright": "#3a3939",
        "inverse-surface": "#e5e2e1",
        "primary-fixed": "#7df4ff",
        "surface-container-low": "#1c1b1b",
        "on-surface-variant": "#b9cacb",
        "on-tertiary": "#480081",
        "surface-tint": "#00dbe9",
        "surface-dim": "#131313",
        "tertiary-fixed-dim": "#dcb8ff",
        "surface-container": "#201f1f",
        "on-error": "#690005",
        "primary-fixed-dim": "#00dbe9",
        "surface-container-lowest": "#0e0e0e",
        "error-container": "#93000a",
        "surface-container-highest": "#353534",
        "surface-container-high": "#2a2a2a",
        secondary: "#ffb3b2",
        "on-primary-fixed-variant": "#004f54",
        "tertiary-fixed": "#efdbff",
        "on-tertiary-fixed": "#2c0051",
        background: "#131313",
        "on-secondary": "#680012",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353534",
        "on-primary-container": "#006970",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)"],
        body: ["var(--font-inter)"],
        label: ["var(--font-inter)"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
export default config;
